# Generated by Django 5.1.2 on 2024-11-13 09:05

import se_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("se_app", "0002_customer_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="address",
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name="customer",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("N", "New"),
                    ("P", "In Process"),
                    ("S", "Sent"),
                    ("C", "Completed"),
                ],
                max_length=1,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=10,
                validators=[se_app.models.validate_positive],
            ),
        ),
    ]
