# Generated by Django 5.1.2 on 2024-11-20 11:13

import se_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("se_app", "0003_alter_customer_address_alter_customer_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[se_app.models.validate_positive],
            ),
        ),
    ]
