# Generated by Django 5.1.2 on 2024-12-04 09:32

import se_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("se_app", "0004_alter_product_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=50,
                validators=[se_app.models.validate_positive],
            ),
        ),
    ]
