name: software-engineering-list-

on:
  push:
    branches:
      - master

  docs:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m venv se_env
          source se_env/bin/activate
          pip install -r requirements.txt

      - name: Generate API documentation
        run: |
          source se_env/bin/activate
          python software_engineering_list7/manage.py generateschema > docs.json
      - name: Commit and push documentation
        run: |
          git config --global user.mail "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add docs.json index.html
          git commit -m "Updated documentation"
          git push origin master
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}